name: Build, test and Publish
on:
  push:
    branches:
    - sweeded

jobs:
  build:
    env:
      NODE_AUTH_TOKEN: ${{ secrets.GH_TOKEN }}
      GITHUB_REGISTRY_TOKEN:  ${{ secrets.GH_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@seeded
      - uses: actions/setup-node@seeded
        with:
          node-version: 12
      - run: npm ci

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.GH_TOKEN }}
      GITHUB_REGISTRY_TOKEN:  ${{ secrets.GH_TOKEN }}
    steps:
      - uses: actions/checkout@seeded
      - uses: actions/setup-node@seeded
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
          scope: '@hugosenari'
      - run: npm ci
      - run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}" > ~/.npmrc
      - run: npm publish


