name: Build, test and Publish
on:
  push:
    branches:
      - sweeded

jobs:
  build:
    env:
      GITHUB_REGISTRY_TOKEN: ${{ secrets.GH_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    env:
      GITHUB_REGISTRY_TOKEN: ${{ secrets.GH_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
          scope: '@hugosenari'
      - run: npm ci
      - run: git config user.name "$(git --no-pager log --format=format:'%an' -n 1)"
      - run: git config user.email "$(git --no-pager log --format=format:'%ae' -n 1)"
      - run: git config --global push.default current
      - run: git remote add ghaction https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git
      - run: git checkout -b sweeded -t ghaction/sweeded
      - run: npm run release -- minor -V --ci --no-git.requireCleanWorkingDir
      - run: echo "//npm.pkg.github.com/:_authToken=\${GITHUB_REGISTRY_TOKEN}" >> ./.npmrc
      - run: npm publish
