name: Build, test and Publish
on:
  push:
    branches:
      - sweeded

jobs:
  build:
    env:
      GITHUB_REGISTRY_TOKEN: ${{ secrets.GH_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    env:
      GITHUB_REGISTRY_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
          scope: '@hugosenari'
      - run: npm ci
      - run: echo "//npm.pkg.github.com/:_authToken=${GITHUB_REGISTRY_TOKEN}" >> ./.npmrc
      - run: git remote add github "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git"
      - run: git branch -u origin/sweeded
      - run: npm run release -- minor --ci --no-git.requireCleanWorkingDir
      # - run: npm publish
